### ISSUE TITLE
Add warning/error on non-sensical cases like width<0 or height<0

### ISSUE THREAD

**Issue by jonnor** [gss/engine#159] opened 2015-02-02 23:55 UTC
Can take a long time to figure these kind of problems without it.
At least show when using ?log=1

**Comment by paulyoung** [comment] 2015-02-03 00:01
Duplicate of #52.

**Comment by Inviz** [comment] 2015-02-03 01:37
Thanks, Paul!

Now it calls engine.console.warn so it's only visible with ?log=1

**Closed by Inviz** 2015-02-03 01:37 UTC
